export const funding = [
    'Expansion and Growth', 'Marketin and advertising', 'Equipment and Infrastructure', 'Data Refinancing', 'Other Reasons']
    export const  industrySectors = [
        "Agriculture",
        "Automotive",
        "Banking & Finance",
        "Construction",
        "Consumer Goods",
        "Education",
        "Energy & Utilities",
        "Entertainment & Media",
        "Fashion & Apparel",
        "Food & Beverage",
        "Healthcare & Pharmaceuticals",
        "Hospitality & Tourism",
        "Information Technology",
        "Insurance",
        "Legal Services",
        "Logistics & Transportation",
        "Manufacturing",
        "Marketing & Advertising",
        "Mining & Metals",
        "Nonprofit & Social Services",
        "Oil & Gas",
        "Real Estate",
        "Retail",
        "Telecommunications",
        'Others',
    ]
      